# Generated by Django 5.2.17 on 2026-09-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
